import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!;
const BOT_TOKEN=Deno.env.get('TELEGRAM_BOT_TOKEN')!;
const BOT_USERNAME=(Deno.env.get('TELEGRAM_BOT_USERNAME')||'Astshara_app_bot').replace(/^@/,'');
const WEBHOOK_SECRET=Deno.env.get('TELEGRAM_WEBHOOK_SECRET')||'';
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{autoRefreshToken:false,persistSession:false}});
const authClient=createClient(SUPABASE_URL,ANON_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const normalizeDigits=(v:string)=>String(v||'').replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c)));
const normalizePhone=(v:string)=>{let p=normalizeDigits(v).trim().replace(/\s+/g,'').replace(/[()\-]/g,'').replace(/[^0-9+]/g,'');if(p.startsWith('+'))p=p.slice(1);if(p.startsWith('00'))p=p.slice(2);if(p.startsWith('0'))p=`964${p.slice(1)}`;if(!p.startsWith('964'))p=`964${p}`;return p};
const phoneCandidates=(p:string)=>[p,`0${p.slice(3)}`,`+${p}`];
const normalizeCode=(v:string)=>normalizeDigits(v).replace(/\s/g,'');
const sha256=async(t:string)=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')};
const randomPassword=()=>crypto.randomUUID()+crypto.randomUUID();
const syntheticEmail=(p:string)=>`telegram.${p}@login.astshara.app`;
const LINKED='هذا الحساب مرتبط بحساب آخر في تطبيق استشارة.';
async function telegram(m:string,b:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${m}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(!d.ok)throw new Error(d.description||`Telegram ${m} failed`);return d.result}
async function ensureWebhook(){const body:Record<string,unknown>={url:`${SUPABASE_URL}/functions/v1/telegram-auth-v2?webhook=1`,allowed_updates:['message'],drop_pending_updates:false};if(WEBHOOK_SECRET)body.secret_token=WEBHOOK_SECRET;await telegram('setWebhook',body)}
async function findProfile(p:string){const{data,error}=await admin.from('profiles').select('*').in('phone',phoneCandidates(p)).limit(1).maybeSingle();if(error)throw new Error(`تعذر التحقق من الرقم: ${error.message}`);return data}
async function findProfileById(id:string){if(!id)return null;const{data,error}=await admin.from('profiles').select('*').eq('id',id).maybeSingle();if(error)throw new Error(`تعذر استرجاع الحساب المرتبط: ${error.message}`);return data}
async function findTelegramProfile(id:number){const{data,error}=await admin.from('profiles').select('*').eq('telegram_user_id',id).limit(1).maybeSingle();if(error)throw new Error(`تعذر التحقق من حساب Telegram: ${error.message}`);return data}
async function start(phoneRaw:string,mode='login',fullName?:string,role?:string){const phone=normalizePhone(phoneRaw);if(!/^9647\d{9}$/.test(phone))throw new Error('رقم الهاتف العراقي غير صحيح');const signup=mode==='signup';if(signup){if(!fullName||fullName.trim().length<3)throw new Error('الاسم الكامل مطلوب');if(role!=='user'&&role!=='lawyer')throw new Error('نوع الحساب غير صحيح');if(await findProfile(phone))throw new Error('هذا الرقم مرتبط بحساب آخر. يرجى استخدام رقم هاتف آخر أو تسجيل الدخول بالحساب المرتبط به.')}await ensureWebhook();const token=crypto.randomUUID();await admin.from('telegram_login_requests').update({status:'expired'}).eq('phone',phone).in('status',['waiting','code_sent','telegram_verified']);const{error}=await admin.from('telegram_login_requests').insert({request_token:token,phone,status:'waiting',attempts:0,expires_at:new Date(Date.now()+600000).toISOString(),mode:signup?'signup':'login',full_name:signup?fullName!.trim():null,role:signup?role:null});if(error)throw new Error(`تعذر إنشاء طلب Telegram: ${error.message}`);return{ok:true,request_token:token,telegram_url:`https://t.me/${BOT_USERNAME}?start=${token}`}}
async function webhook(req:Request){if(WEBHOOK_SECRET&&req.headers.get('x-telegram-bot-api-secret-token')!==WEBHOOK_SECRET)return json({ok:false},401);const u=await req.json(),m=u?.message;if(!m?.chat?.id)return json({ok:true});if(m.contact){await handleContact(m);return json({ok:true})}const id=Number(m.chat.id),text=String(m.text||'').trim(),arg=text.match(/^\/start(?:\s+(.+))?$/i)?.[1]?.trim();if(!arg){await telegram('sendMessage',{chat_id:id,text:'مرحباً بك في بوت استشارة ⚖️\nافتح رابط تسجيل الدخول من تطبيق استشارة واضغط «بدء». ثم اختر «مشاركة رقم الهاتف» لإكمال الدخول تلقائياً.'});return json({ok:true})}const{data:r,error}=await admin.from('telegram_login_requests').select('*').eq('request_token',arg).maybeSingle();if(error||!r||new Date(r.expires_at).getTime()<=Date.now()||r.status==='expired'){await telegram('sendMessage',{chat_id:id,text:'انتهت صلاحية طلب التحقق. ارجع إلى تطبيق استشارة واطلب محاولة جديدة.'});return json({ok:true})}const existing=await findTelegramProfile(id);if(existing){if(r.mode==='login'){await admin.from('telegram_login_requests').update({telegram_user_id:id,status:'telegram_verified',verified_profile_id:existing.id,telegram_username:m.from?.username??null,telegram_first_name:m.from?.first_name??null,telegram_last_name:m.from?.last_name??null}).eq('id',r.id);await telegram('sendMessage',{chat_id:id,text:'تم التحقق من حساب Telegram. ارجع إلى استشارة، وسيتم تسجيل دخولك تلقائياً.'});return json({ok:true})}await telegram('sendMessage',{chat_id:id,text:LINKED});return json({ok:true})}await admin.from('telegram_login_requests').update({telegram_user_id:id,telegram_username:m.from?.username??null,telegram_first_name:m.from?.first_name??null,telegram_last_name:m.from?.last_name??null}).eq('id',r.id);await telegram('sendMessage',{chat_id:id,text:'لإكمال تسجيل الدخول تلقائياً، اضغط الزر أدناه لمشاركة رقم هاتفك مع بوت استشارة. لن يتم استخدامه إلا للتحقق من ملكية الرقم.',reply_markup:{keyboard:[[{text:'مشاركة رقم الهاتف',request_contact:true}]],resize_keyboard:true,one_time_keyboard:true}});return json({ok:true})}
async function handleContact(m:any){const id=Number(m.chat.id),contact=m.contact;if(!contact?.phone_number)return false;const contactPhone=normalizePhone(String(contact.phone_number));const{data:r,error}=await admin.from('telegram_login_requests').select('*').eq('telegram_user_id',id).eq('status','waiting').order('created_at',{ascending:false}).limit(1).maybeSingle();if(error||!r)return false;if(new Date(r.expires_at).getTime()<=Date.now()){await admin.from('telegram_login_requests').update({status:'expired'}).eq('id',r.id);return false}if(contactPhone!==normalizePhone(r.phone)){await telegram('sendMessage',{chat_id:id,text:'رقم الهاتف الذي تمت مشاركته لا يطابق الرقم المدخل في استشارة. ارجع إلى التطبيق وتحقق من الرقم.',reply_markup:{remove_keyboard:true}});return true}const existingTelegram=await findTelegramProfile(id);if(existingTelegram&&r.mode==='login'){await admin.from('telegram_login_requests').update({status:'telegram_verified',verified_profile_id:existingTelegram.id,telegram_user_id:id,verified_at:null}).eq('id',r.id);await admin.from('profiles').update({telegram_user_id:id,updated_at:new Date().toISOString()}).eq('id',existingTelegram.id);await telegram('sendMessage',{chat_id:id,text:'تم التحقق بنجاح. ارجع إلى استشارة، وسيتم تسجيل دخولك تلقائياً.',reply_markup:{remove_keyboard:true}});return true}const profile=await findProfile(r.phone);if(r.mode==='login'&&!profile){await telegram('sendMessage',{chat_id:id,text:'لم يتم العثور على حساب بهذا الرقم. أنشئ حساباً أولاً من استشارة.',reply_markup:{remove_keyboard:true}});return true}if(r.mode==='signup'&&profile){await telegram('sendMessage',{chat_id:id,text:'هذا الرقم مرتبط بحساب موجود. استخدم تسجيل الدخول بدلاً من إنشاء حساب جديد.',reply_markup:{remove_keyboard:true}});return true}await admin.from('telegram_login_requests').update({status:'telegram_verified',verified_profile_id:profile?.id??null,verified_at:null,telegram_user_id:id,telegram_username:m.from?.username??null,telegram_first_name:m.from?.first_name??null,telegram_last_name:m.from?.last_name??null}).eq('id',r.id);if(profile?.id)await admin.from('profiles').update({telegram_user_id:id,updated_at:new Date().toISOString()}).eq('id',profile.id);await telegram('sendMessage',{chat_id:id,text:'تم التحقق بنجاح. ارجع إلى استشارة، وسيتم إكمال العملية تلقائياً.',reply_markup:{remove_keyboard:true}});return true}
async function status(token:string){const{data:r,error}=await admin.from('telegram_login_requests').select('status,expires_at,telegram_user_id,mode').eq('request_token',token).maybeSingle();if(error)throw new Error(error.message);if(!r)throw new Error('طلب التحقق غير موجود');if(new Date(r.expires_at).getTime()<=Date.now()&&r.status!=='verified')return{ok:false,status:'expired'};return{ok:true,status:r.status,telegram_linked:!!r.telegram_user_id,mode:r.mode}}
async function createSessionForProfile(r:any,p:any){if(!p?.auth_id)throw new Error('تعذر استرجاع الحساب المرتبط');const user=(await admin.auth.admin.getUserById(p.auth_id)).data.user;if(!user)throw new Error('تعذر استرجاع الحساب');const email=user.email||syntheticEmail(r.phone),password=randomPassword();const{error:ue}=await admin.auth.admin.updateUserById(user.id,{password,user_metadata:{...(user.user_metadata||{}),full_name:p.full_name,role:p.role}});if(ue)throw new Error(`تعذر تجهيز جلسة الدخول: ${ue.message}`);const{data:login,error:le}=await authClient.auth.signInWithPassword({email,password});if(le||!login.session)throw new Error(`تعذر إنشاء جلسة الدخول: ${le?.message||'الجلسة غير متاحة'}`);await admin.from('profiles').update({telegram_user_id:r.telegram_user_id,updated_at:new Date().toISOString()}).eq('id',p.id);await admin.from('telegram_login_requests').update({status:'verified',verified_at:new Date().toISOString(),verified_profile_id:p.id}).eq('id',r.id);return{ok:true,access_token:login.session.access_token,refresh_token:login.session.refresh_token,userId:user.id}}
async function verify(token:string,rawCode?:string){const{data:r,error}=await admin.from('telegram_login_requests').select('*').eq('request_token',token).maybeSingle();if(error)throw new Error(error.message);if(!r)throw new Error('طلب التحقق غير موجود');if(new Date(r.expires_at).getTime()<=Date.now()){await admin.from('telegram_login_requests').update({status:'expired'}).eq('id',r.id);throw new Error('انتهت صلاحية رمز التحقق. اطلب رمزاً جديداً')}if(r.mode==='login'&&r.status==='telegram_verified'&&r.telegram_user_id){const p=(r.verified_profile_id?await findProfileById(r.verified_profile_id):await findTelegramProfile(Number(r.telegram_user_id)))||await findProfile(r.phone);if(!p)throw new Error('لم يتم العثور على الحساب المرتبط بهذا الرقم');return await createSessionForProfile(r,p)}const code=normalizeCode(rawCode||'');if(!r.telegram_user_id||r.status!=='code_sent')throw new Error('لم تصل إشارة Telegram بعد. افتح Telegram واضغط «بدء» من رابط استشارة، ثم انتظر وصول الرمز.');if(!/^\d{6}$/.test(code))throw new Error('رمز التحقق يجب أن يتكون من 6 أرقام');if((r.attempts??0)>=5)throw new Error('تم تجاوز عدد المحاولات المسموح بها. اطلب رمزاً جديداً');const expected=await sha256(`${code}:${token}`);if(expected!==r.code_hash){await admin.from('telegram_login_requests').update({attempts:(r.attempts??0)+1}).eq('id',r.id);throw new Error('رمز التحقق غير صحيح')}const phone=r.phone,mode=r.mode||'login',profile=await findProfile(phone),tp=await findTelegramProfile(Number(r.telegram_user_id));if(tp&&(!profile||tp.id!==profile.id))throw new Error(LINKED);if(mode==='signup'&&profile)throw new Error('هذا الرقم مرتبط بحساب آخر. يرجى استخدام رقم هاتف آخر أو تسجيل الدخول بالحساب المرتبط به.');if(mode==='login'&&!profile)throw new Error('لم يتم العثور على حساب مرتبط بهذا الرقم. يرجى إنشاء حساب أولاً.');let authUser:any;if(profile?.auth_id)authUser=(await admin.auth.admin.getUserById(profile.auth_id)).data.user;else{const email=syntheticEmail(phone),password=randomPassword(),role=r.role==='lawyer'?'lawyer':'user',fullName=String(r.full_name||'').trim();const{data:created,error:ce}=await admin.auth.admin.createUser({email,password,email_confirm:true,phone:`+${phone}`,phone_confirm:true,user_metadata:{full_name:fullName,role}});if(ce)throw new Error(/already|exists|registered|duplicate/i.test(ce.message)?LINKED:`تعذر إنشاء الحساب: ${ce.message}`);authUser=created.user;const{error:ie}=await admin.from('profiles').insert({auth_id:authUser.id,phone,email,full_name:fullName,role,telegram_user_id:r.telegram_user_id});if(ie){await admin.auth.admin.deleteUser(authUser.id);if(ie.code==='23505')throw new Error(LINKED);throw new Error(`تعذر إنشاء ملف المستخدم: ${ie.message}`)}}return await createSessionForProfile(r,profile||await findProfile(phone))}
Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response('ok',{status:200,headers:cors});const url=new URL(req.url);if(req.method==='POST'&&url.searchParams.get('webhook')==='1')return await webhook(req);if(req.method!=='POST')return json({error:'Method not allowed'},405);const body=await req.json();const action=String(body?.action||'');if(action==='start')return json(await start(String(body?.phone||''),String(body?.mode||'login'),body?.full_name,body?.role));if(action==='status')return json(await status(String(body?.request_token||'')));if(action==='verify')return json(await verify(String(body?.request_token||''),String(body?.code||'')));return json({error:'إجراء غير معروف'},400)}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400)}});
