import 'package:flutter/material.dart';
import 'package:astshara/core/config/supabase_config.dart';

class LawyerWalletPage extends StatefulWidget { const LawyerWalletPage({super.key}); @override State<LawyerWalletPage> createState()=>_LawyerWalletPageState(); }
class _LawyerWalletPageState extends State<LawyerWalletPage> {
 Map<String,dynamic>? wallet; String? walletType,walletNumber,walletHolder; List<Map<String,dynamic>> requests=[]; bool loading=true,submitting=false,saving=false;
 static const types={'zain_cash':'زين كاش','asia_hawala':'آسيا حوالة','qi_card':'Qi Card'};
 @override void initState(){super.initState();_load();}
 Future<void> _load() async { if(mounted)setState(()=>loading=true); try{ final u=SupabaseConfig.client.auth.currentUser;if(u==null)throw Exception('يجب تسجيل الدخول'); final p=await SupabaseConfig.client.from('profiles').select('id,wallet_type,wallet_number,wallet_holder_name').eq('auth_id',u.id).maybeSingle();if(p==null)throw Exception('ملف المحامي غير موجود'); walletType=p['wallet_type']?.toString();walletNumber=p['wallet_number']?.toString();walletHolder=p['wallet_holder_name']?.toString(); wallet=await SupabaseConfig.client.from('lawyer_wallets').select().eq('lawyer_id',p['id']).maybeSingle(); requests=List<Map<String,dynamic>>.from(await SupabaseConfig.client.from('lawyer_payout_requests').select('id,amount,currency,status,wallet_type,wallet_number,wallet_holder_name,created_at,rejection_reason,provider_reference').eq('lawyer_id',p['id']).order('created_at',ascending:false).limit(20)); }catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> _editMethod() async { String type=walletType??'zain_cash'; final n=TextEditingController(text:walletNumber??'');final h=TextEditingController(text:walletHolder??''); final result=await showDialog<List<String>>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setD)=>AlertDialog(title:const Text('طريقة استلام المستحقات'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(value:type,decoration:const InputDecoration(labelText:'نوع الوسيلة'),items:types.entries.map((e)=>DropdownMenuItem(value:e.key,child:Text(e.value))).toList(),onChanged:(v){if(v!=null)setD(()=>type=v);}),const SizedBox(height:12),TextField(controller:n,keyboardType:TextInputType.phone,textDirection:TextDirection.ltr,decoration:InputDecoration(labelText:type=='qi_card'?'رقم البطاقة / الحساب':'رقم الهاتف')),const SizedBox(height:12),TextField(controller:h,decoration:const InputDecoration(labelText:'اسم صاحب الوسيلة')),]),),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(c,[type,n.text.trim(),h.text.trim()]),child:const Text('حفظ'))])));n.dispose();h.dispose();if(result==null)return;setState(()=>saving=true);try{await SupabaseConfig.client.rpc('update_own_lawyer_wallet_details',params:{'p_wallet_type':result[0],'p_wallet_number':result[1],'p_wallet_holder_name':result[2]});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حفظ وسيلة الاستلام')));await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر الحفظ: ${e.toString().replaceFirst('Exception: ', '')}')));}finally{if(mounted)setState(()=>saving=false);}}
 Future<void> _payout() async {if(walletType==null||walletNumber==null||walletHolder==null){await _editMethod();if(walletType==null||walletNumber==null||walletHolder==null)return;}final available=num.tryParse('${wallet?['available_balance']??0}')??0;if(available<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('لا يوجد رصيد متاح للسحب')));return;}final c=TextEditingController();final amount=await showDialog<double>(context:context,builder:(d)=>AlertDialog(title:const Text('طلب سحب'),content:Column(mainAxisSize:MainAxisSize.min,children:[Text('المتاح: ${money(available)}'),TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'المبلغ بالدينار العراقي'))]),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,double.tryParse(c.text.trim())),child:const Text('إرسال'))]));c.dispose();if(amount==null||amount<=0||amount>available)return;setState(()=>submitting=true);try{await SupabaseConfig.client.rpc('request_lawyer_payout',params:{'p_amount':amount});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم إرسال طلب السحب إلى الإدارة')));await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر تنفيذ الطلب: ${e.toString().replaceFirst('Exception: ', '')}')));}finally{if(mounted)setState(()=>submitting=false);}}
 String money(dynamic v)=>'${(num.tryParse('${v??0}')??0).toStringAsFixed(0)} د.ع';String status(String v)=>{'pending_review':'بانتظار مراجعة الإدارة','approved':'تمت الموافقة','processing':'قيد التنفيذ','paid':'تم التحويل','rejected':'مرفوض','failed':'فشل التحويل'}[v]??v;
 String date(dynamic v){final d=DateTime.tryParse('${v??''}');if(d==null)return'—';final x=d.toLocal();return'${x.day.toString().padLeft(2,'0')}/${x.month.toString().padLeft(2,'0')}/${x.year}';}
 @override Widget build(BuildContext context){final w=wallet??{};return Scaffold(appBar:AppBar(title:const Text('محفظتي المالية')),body:RefreshIndicator(onRefresh:_load,child:loading?ListView(children:const[ SizedBox(height:300),Center(child:CircularProgressIndicator())]):ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('الرصيد المتاح'),Text(money(w['available_balance']),style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const SizedBox(height:14),Row(children:[Expanded(child:_s('معلق',money(w['pending_balance']))),Expanded(child:_s('إجمالي الأرباح',money(w['lifetime_earned']))),Expanded(child:_s('المسحوبات',money(w['lifetime_paid_out'])))]),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:submitting?null:_payout,icon:const Icon(Icons.payments_outlined),label:const Text('طلب سحب')))]))),const SizedBox(height:14),Card(child:ListTile(leading:const Icon(Icons.account_balance_wallet_outlined),title:Text(walletType==null?'وسيلة الاستلام غير مضافة':'وسيلة الاستلام: ${types[walletType]??walletType}',subtitle:Text(walletNumber==null?'أضف وسيلة استلام المستحقات':'$walletNumber\n${walletHolder??''}'),trailing:saving?const SizedBox(width:22,height:22,child:CircularProgressIndicator()):IconButton(onPressed:_editMethod,icon:const Icon(Icons.edit_outlined)))),const SizedBox(height:20),const Text('طلبات السحب',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...requests.map((r)=>Card(child:ListTile(leading:const Icon(Icons.receipt_long_outlined),title:Text(money(r['amount'])),subtitle:Text('${types[r['wallet_type']]??r['wallet_type']} • ${r['wallet_number']??''}\n${status('${r['status']}')} • ${date(r['created_at'])}${r['rejection_reason']!=null?'\nسبب الرفض: ${r['rejection_reason']}':''}${r['provider_reference']!=null?'\nمرجع التحويل: ${r['provider_reference']}':''}'))))])));}
 Widget _s(String a,String b)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:11)),Text(b,style:const TextStyle(fontWeight:FontWeight.w700))]);
}
