import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const auth=req.headers.get('Authorization');if(!auth)throw new Error('غير مصرح');
 const url=Deno.env.get('SUPABASE_URL')!,sr=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!;
 const base=(Deno.env.get('QICARD_API_URL')||Deno.env.get('QICARD_API_BASE_URL')||'https://uat-sandbox-3ds-api.qi.iq/api/v1').replace(/\/$/,'');
 const username=Deno.env.get('QICARD_USERNAME'),password=Deno.env.get('QICARD_PASSWORD'),terminal=Deno.env.get('QICARD_TERMINAL_ID');if(!username||!password||!terminal)throw new Error('بيانات بوابة كي كارد غير مكتملة');
 const client=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:ud,error:ae}=await client.auth.getUser();if(ae||!ud.user)throw new Error('المستخدم غير مسجل دخول');
 const {booking_id}=await req.json();if(!booking_id)throw new Error('معرّف الحجز مطلوب');const admin=createClient(url,sr);
 const {data:b,error:be}=await admin.from('bookings').select('id,user_id,price,status,lawyer_approved').eq('id',booking_id).maybeSingle();if(be)throw be;if(!b||b.user_id!==ud.user.id)throw new Error('لا تملك صلاحية هذا الحجز');
 const {data:ps,error:pe}=await admin.from('payments').select('id,booking_id,qicard_payment_id,status,qicard_raw_status,created_at').eq('booking_id',booking_id).not('qicard_payment_id','is',null).order('created_at',{ascending:false});if(pe)throw pe;if(!ps?.length)throw new Error('لا توجد عملية كي كارد مرتبطة بهذا الحجز');
 const credentials=btoa(`${username}:${password}`);let final:any=null,pending:any=null;const checks:any[]=[];
 for(const p of ps){try{const r=await fetch(`${base}/payment/${encodeURIComponent(p.qicard_payment_id)}/status`,{headers:{Accept:'application/json',Authorization:`Basic ${credentials}`,"X-Terminal-Id":terminal}});const text=await r.text();let d:any;try{d=JSON.parse(text)}catch{d=null}checks.push({payment_id:p.id,qicard_payment_id:p.qicard_payment_id,http_status:r.status,body:text.slice(0,500)});if(!r.ok)continue;const raw=String(d?.status||'').toUpperCase();if(Number(d?.amount)!==Number(b.price)||String(d?.currency||'')!=='IQD')continue;if(raw==='SUCCESS'||raw==='FAILED'||raw==='AUTHENTICATION_FAILED'){final={p,d,raw};break;}if(!pending)pending={p,d,raw};}catch(e){checks.push({payment_id:p.id,error:e instanceof Error?e.message:'request failed'});}}
 if(!final&&!pending)return new Response(JSON.stringify({payment_status:'قيد معالجة الدفع',booking_status:b.status,checks}),{status:200,headers:{...cors,'Content-Type':'application/json'}});
 const {p,d,raw}=(final||pending);const success=raw==='SUCCESS',failed=raw==='FAILED'||raw==='AUTHENTICATION_FAILED';const mapped=success?'تم الدفع':failed?'فشل الدفع':'قيد معالجة الدفع';const now=new Date().toISOString();
 const {error:ue}=await admin.from('payments').update({status:mapped,qicard_raw_status:raw,qicard_payment_type:d?.paymentType??null,qicard_payment_system:d?.details?.paymentSystem??null,qicard_rrn:d?.details?.rrn??null,qicard_auth_id:d?.details?.authId??null,qicard_updated_at:now,verified_at:success?now:null}).eq('id',p.id);if(ue)throw ue;
 const bookingStatus=success?(b.lawyer_approved?'مؤكد':'قيد مراجعة المحامي'):failed?'قيد انتظار الدفع':'قيد معالجة الدفع';const {error:bu}=await admin.from('bookings').update({status:bookingStatus}).eq('id',b.id);if(bu)throw bu;
 return new Response(JSON.stringify({payment_status:mapped,qicard_status:raw,booking_status:bookingStatus,payment_id:p.id,qicard_payment_id:p.qicard_payment_id,checks}),{status:200,headers:{...cors,'Content-Type':'application/json'}});
}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:'حدث خطأ غير متوقع'}),{status:400,headers:{...cors,'Content-Type':'application/json'}})}});