import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/bookings_provider.dart';
import '../../domain/entities/booking.dart';

class ManualPaymentPage extends ConsumerStatefulWidget { final Booking booking; const ManualPaymentPage({super.key,required this.booking}); @override ConsumerState<ManualPaymentPage> createState()=>_ManualPaymentPageState(); }
class _ManualPaymentPageState extends ConsumerState<ManualPaymentPage> {
  final _amount=TextEditingController(); bool _saving=false;
  @override void dispose(){_amount.dispose();super.dispose();}
  Future<void> _save() async {final amount=double.tryParse(_amount.text.trim().replaceAll(',',''));if(amount==null||amount<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('أدخل مبلغاً صحيحاً أكبر من صفر.')));return;}setState(()=>_saving=true);try{final updated=await ref.read(bookingsControllerProvider.notifier).recordManualPayment(bookingId:widget.booking.id,amount:amount);if(!mounted)return;if(updated==null){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ref.read(bookingsControllerProvider).error?.toString()??'تعذر تسجيل الدفع')));return;}ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم تسجيل المبلغ المستلم وتأكيد الدفع.')));Navigator.pop(context,updated);}finally{if(mounted)setState(()=>_saving=false);}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('تسجيل الدفع اليدوي')),body:ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(borderRadius:BorderRadius.circular(16),color:Theme.of(context).colorScheme.primary.withValues(alpha:.08)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('الدفع في المكتب',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),Text('لن يتم اعتبار الحجز مدفوعاً ولن تتمكن من بدء الاستشارة حتى تسجل المبلغ الذي استلمته فعلياً من الموكل.')]),),const SizedBox(height:24),Text('المبلغ المطلوب حسب الحجز: ${widget.booking.price} د.ع',style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:12),TextField(controller:_amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'المبلغ المستلم فعلياً (د.ع)',hintText:'مثلاً 75000',border:OutlineInputBorder())),const SizedBox(height:24),ElevatedButton.icon(onPressed:_saving?null:_save,icon:const Icon(Icons.check_circle_outline),label:Text(_saving?'جاري الحفظ...':'تسجيل المبلغ وتأكيد الدفع'),style:ElevatedButton.styleFrom(minimumSize:const Size.fromHeight(52))) ]));
}
